services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./better-auth_migrations:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes:
  db-data:
